# This is a GitHub Actions workflow file.
# It defines a set of automated jobs.

# Name of the workflow, which will be displayed in the Actions tab on GitHub.
name: 'Run YAML Stats Script'

# This section defines the trigger for the workflow.
on:
  # We want to trigger this workflow on 'push' events to the repository.
  push:
    # But ONLY if the push includes changes to the specified file.
    # This prevents the script from running on every single push.
    paths:
      - 'prominence/list_of_prominent_functions.yaml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # We define a single job called 'build'.
  build:
    # The type of virtual machine to run the job on. 'ubuntu-latest' is a common and reliable choice.
    runs-on: ubuntu-latest

    # 'steps' represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Check out the repository's code.
      # This action downloads a copy of your repository onto the runner,
      # so the workflow can access your script and YAML file.
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment.
      # This action installs a specific version of Python on the runner.
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies.
      # Your Python script needs the 'PyYAML' library to run.
      # This step uses pip to install it.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      # Step 4: Run the Python script.
      # This command executes your script, which will now generate a stats_report.md file.
      - name: Run the stats script
        run: python ./.github/workflows/yaml_stats_script.py

      # Step 5: Commit the generated stats file.
      # This step checks for changes in the repository (specifically the new report file)
      # and commits them back to the main branch.
      - name: Commit stats report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # The commit message for the update.
          commit_message: 'docs: Update YAML stats report'
          # The file pattern to look for. We only want to commit the markdown report file.
          file_pattern: 'statistics/stats_report.md'
          # The author of the commit.
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions Bot <actions@github.com>'
