name: Convert YAML to Markdown

on:
  push:
    paths:
      - 'secretaries_of_state/mapping.yaml'

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PyYAML
      run: pip install pyyaml

    - name: Convert YAML to Markdown
      run: |
        python3 <<EOF
        import yaml

        with open('secretaries_of_state/mapping.yaml', 'r') as f:
            data = yaml.safe_load(f)

        def to_markdown(data, level=1):
            md = ''
            if isinstance(data, dict):
                for key, value in data.items():
                    md += '#' * level + f' {key}\
\
'
                    md += to_markdown(value, level + 1)
            elif isinstance(data, list):
                for item in data:
                    md += '- ' + str(item) + '\
'
            else:
                md += str(
