name: Convert YAML to Markdown

on:
  push:
    paths:
      - 'secretaries_of_state/mapping.yaml'

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Convert YAML to Markdown Table
        run: |
          python3 <<EOF
          import yaml

          with open('secretaries_of_state/mapping.yaml', 'r') as f:
              data = yaml.safe_load(f)

          headers = ["Secretary", "Wikidata ID", "Department"]
          rows = []

          for secretary, details in data.items():
              wikidata = details.get("Wikidata identifier", "").strip()
              department = details.get("Department", "").strip()
              rows.append([secretary.strip(), wikidata, department])

          # Start with invisible edit warning
          md = "<!-- ⚠️ This file is auto-generated from mapping.yaml. Do not edit it manually. -->\\n\\n"

          # Build Markdown table
          md += f"| {' | '.join(headers)} |\\n"
          md += f"| {' | '.join(['-' * len(h) for h in headers])} |\\n"
          for row in rows:
              md += f"| {' | '.join(row)} |\\n"

          with open('secretaries_of_state/mapping.md', 'w') as f:
              f.write(md)
          EOF

      - name: Commit Markdown file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add secretaries_of_state/mapping.md
          git status
          git diff
          git commit -m "Update Markdown from YAML" || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
